### ISSUE TITLE
Timeout for fuzzers defaults to 0

### ISSUE THREAD

**Issue by neuromancer** [trailofbits/deepstate#290]
https://github.com/trailofbits/deepstate/blob/master/bin/deepstate/core/fuzz.py#L124

**Comment by agroce** [comment]
Hmm, looks simple to fix; should be 3600 @ex0dus-0x right?  Doesn't look like most executors override....

**Comment by ex0dus-0x** [comment]
Use [here](https://github.com/trailofbits/deepstate/blob/master/bin/deepstate/core/fuzz.py#L463) was done in order to signify that if `self.timeout` is set to a default 0, there would be no timeout enforced and the process would run indefinitely. Found that running executors on a container worker with a finite implicit timeout led to it dying before exploring all paths, and may not be ideal when we might continuously run an executor to maximize crashes to be found.

**Comment by neuromancer** [comment]
I tested it with eclipser and it stops as soon as the tool starts (so it is very confusing from the user perspective).

**Comment by agroce** [comment]
Yeah, I am pretty sure this needs overridden for sensible Eclipser behavior.
