### ISSUE TITLE
libfuzzer build ignores DeepState command line args, leaving no way turn down output verbosity

### ISSUE THREAD

**Issue by laurynas-biveinis** [trailofbits/deepstate#376]
A libfuzzer build only parses libfuzzer args but not DeepState ones. This leaves no way to turn down output verbosity, which includes TRACE level at least, and easily produces gigabytes of logs per minutes of fuzzing.

By source code reading it would appear that setting LIBFUZZER_LOUD environment variable would disable any DeepState output, but this does not appear to work.

The docs and runner help suggest using DEEPSTATE_LOG environment variable, but it is only checked at the Python runner, not in the fuzzer executable. Likewise runner's --min_log_level arg has no effect.

This could be fixed by querying DEEPSTATE_LOG environment variable in LLVMFuzzerTestInput

**Comment by agroce** [comment]
I'll take a look to fixing libFuzzer output control soon, it used to "work" but made libFuzzer output mostly invisible even if you wanted it, now it's too hard to shut it up, but I think I know how to fix when I get an hour

**Comment by agroce** [comment]
Didn't forget this; it's just slightly trickier than I thought, will tackle soon, since I find it really annoying myself :)

**Comment by agroce** [comment]
Should be fixed now, let me know if you run into issues.  the behavior with LIBFUZZER_LOUD is not totally intuitive, but setting DEEPSTATE_LOG should really do most things, just note that libfuzzer pretty much HAS to always dump out DEBUG level stuff, since this is what libfuzzer itself looks like (maybe not on mac, have not tested that since getting libfuzzer happy on mac is a pain itself)

**Comment by laurynas-biveinis** [comment]
Confirmed fixed, thank you!
